---
title: "Turkish Sheep Counts"
author: "Sefa Ozalp"
date: "2020-02-07"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r,message=F}
library(tidyverse)
library(janitor)

df <- read_csv(here::here("/data/sheeps.csv")) %>%
  clean_names()


```


## Data

Can be explored using the buttons. 
```{r}
df %>% 
  rmarkdown::paged_table()
```


## Interactive Viz
```{r}
df %>% 
  group_by(yil) %>% 
  summarise(total_koyun =sum(sayi)) %>% 
  plotly::plot_ly(x= ~yil, y=~total_koyun, 
                  type = 'scatter', mode='lines+markers') %>% 
  plotly::layout( title="Sheep Counts in Turkey",
    yaxis = list(range=c(0,40000000), title= "Sheep Count"),
     xaxis = list(title= "Source: TUIK")
    
  )
```

Seems like numbers from @DrDataStats is right.

## Further Exploration

### Sheep trends by sex


```{r,fig.retina=T,fig.height=6, fig.width=8}
df %>% 
  mutate(sheep_type= ifelse(stringr::str_detect(yas, 'Merinos'), "merinos", "other")) %>% 
  mutate(sheep_age= case_when( 
    stringr::str_detect(yas, "6 Aydan Küçük") ~ "6 months", 
    stringr::str_detect(yas, "6 - 12 Ay Arası") ~ "6-12 months", 
    stringr::str_detect(yas, "12 - 24 Ay") ~ "12-24 months", 
    stringr::str_detect(yas, "2 Ve Daha Yukarı") ~ "Over 24 months"
  )) %>% 
  mutate(sheep_sex= case_when( 
    stringr::str_detect(yas, "Koç") ~ "male", 
    stringr::str_detect(yas, "Dişi Koyun") ~ "female", 
    T ~ 'both'
  )) %>% 
  group_by(yil, sheep_sex) %>% 
  summarise(total_koyun =sum(sayi)) %>% 
  ggplot(aes(x=yil, y=total_koyun, colour=sheep_sex))+
  geom_line(size=1)+
  scale_y_continuous(label=scales::comma)+
  hrbrthemes::theme_ipsum_rc()+
  labs(title = "Sheep counts in Turkey, by sex", y="Sheep Count", x="Year", subtitle = "Source: TUIK",caption = "@SefaOzalp, 2020")
  
```

Looks like male sheep trends are stable while female sheep counts have increased steadily. 

